config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:new, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian],
                                    message: '%[value] is not a valid category' }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, numericality: { in: (0..5), message: '%[value] must be between 0 and 5' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    # We need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id]) # -> retaurant_id as we are nested
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save 
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="d-flex justify-content-between m-2">
      <p><%= link_to "Create a new restaurant", new_restaurant_path %></p>
      <p><%= link_to "Back to restaurant list", restaurants_path %></p>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
  <div class="container mt-2 text-center">
      <% @restaurants.each do |restaurant| %>
          <p><%= link_to restaurant.name,restaurant_path(restaurant) %></p>
      <%end%>
  </div>

app/views/restaurants/new.html.erb
<!-- app/views/restaurants/_form.html.erb -->
<h1 class= "text-center mt-3">Create a new restaurant</h1>

<div class="container">
  <div class="row col-6 d-flex justify-content-center mt-3">
    <%= simple_form_for(@restaurant) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container m-2 text-align-center weight-bold">
  <p>Name: <%=@restaurant.name%></p>
  <p>Address: <%=@restaurant.address%></p>
  <p>Phone: <%=@restaurant.phone_number%></p>
  <p>Category: <%=@restaurant.category%></p>
  -------------------------
  <%@restaurant.reviews.each do |review| %>
    <p>Content: <%=review.content%></p>
    <p>Review: <%=review.rating%></p>
  ----------
  <%end%>
</div>

<div class="button btn primary-btn">
  <%=link_to "Add a Review", new_restaurant_review_path(@restaurant)%>
</div>

app/views/reviews/new.html.erb
<!-- app/views/restaurants/_form.html.erb -->
<h1 class= "text-center mt-3">Add a review!</h1>

<div class="container">
  <div class="row col-6 d-flex justify-content-center mt-3">
    <%= simple_form_for([@restaurant, @review]) do |f| %>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.submit %>
    <% end %>
  </div>
</div>